reorder_imports = true
format_strings = true
max_width = 80
merge_imports = true
normalize_comments = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
struct_field_align_threshold = 20
struct_list_single_line = true